config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  scope :recent_messages, -> { order(:created_at).last(15) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username,
            presence: true,
            length: { minimum: 3, maximum: 15 },
            uniqueness: { case_sensivity: false }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.recent_messages
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel',
                                   msg: render_message(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(msg)
    render(partial: 'message', locals: { message: msg })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in!'
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong with your credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular assistive listening systems icon red"></i>
  Say something
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div id="messages-container" class="ui feed">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: 'ui reply form', role: 'form'}, url: message_path, remote: true ) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: 'Enter new message' %>
              <%= f.button '<i class="bordered inverted red icon edit"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Active users
          </a>
          <a class="item">
            TODO
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui inverted small menu">
  <div class="ui container">
    <%= link_to 'Chatroom', root_path, class: 'item' %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Log out', logout_path, method: :delete, class: 'item' %>
          <% else %>
            <%= link_to 'Log in', login_path, class: 'item' %>
          <% end %>
        </div>
      </div>
      <% unless logged_in? %>
        <div class="item">
          <%= link_to 'Sign in', login_path, class: "ui red button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>